# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Sonali Kumar
description: "Hi I'm Sonali, and I'm a HR Analyst based in Upstate NY. I am passionate about people analytics, organization development, Health & Wellness, and process improvement." 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: HR Analyst <span style="color:#add8e6"> Portfolio </span>
location: "Albany, NY"
resume_url: /docs/Sonali_Kumar_Resume.pdf
avatar_image: /img/Sonali_Kumar.jpg

#------------------------------- 
# Contact links
linkedln: "https://www.linkedin.com/in/kumar-sonali/" # Add your linkedln handle
github: "https://github.com/Sonali-Kumar"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

